services:
  postges:
    container_name: postgres
    image: postgres
    restart: on-failure
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - registry-net
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./home/pius/Documents/work/igrid/registry/sql/tables.sql:/docker-entrypoint-initdb.d/
      - registry2-postgres-db-volume:/var/lib/postgresql/data
networks:
  registry-net:

volumes:
  registry2-postgres-db-volume:
