CREATE TABLE IF NOT EXISTS regions(
    id VARCHAR(50) UNIQUE NOT NULL PRIMARY KEY,
    name VARCHAR (100) UNIQUE,
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS nodes(
    uuid VARCHAR(100) UNIQUE NOT NULL PRIMARY KEY,
    addr VARCHAR(100) NOT NULL,
    key VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    type INT NOT NULL,
    region VARCHAR(100) NOT NULL,
    latd VARCHAR(100) NOT NULL,
    long VARCHAR(100) NOT NULL,
    created VARCHAR(100) NOT NULL,
    master VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS users(
    id VARCHAR(100) UNIQUE NOT NULL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    region VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) UNIQUE NOT NULL,
    created VARCHAR(100) UNIQUE NOT NULL
);